services:
  timescale:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  engine:
    depends_on:
      - timescale
    image: ghcr.io/volkovlabs/business-engine:2.3.0
    #env_file: .env
    environment:
      DATABASE_HOST: timescale
      DATABASE_PORT: 5432
      DATABASE_DB: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      GRAFANA_URL: https://MY-ACCOUNT.grafana.net
      GRAFANA_TOKEN: MY-SERVICE_TOKEN
    ports:
      - 3001:3001
      - 3002:3002
