{
 "title": "Website Analytics",
 "description": "NGINX Analytics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "geomap",
   "gridPos": { "h": 17, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (geoip_country_code) (count_over_time({host=~\"$host\"} | json [$__interval]))",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Requests  ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({host=~\"$host\"}[$__interval]))  ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Visitors per Hour",
   "type": "stat",
   "description": "Different IP addresses",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({host=~\"$host\"} | json [$__interval])))"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 14 }
   ]
  },
  {
   "title": "Referers",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (http_referer) (count_over_time({host=~\"$host\"} | json [$__interval]))",
     "legendFormat": "{{http_referer}}"
    }
   ]
  },
  {
   "title": "Successfully Requested Pages",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 17 },
   "targets": [
    {
     "expr": "sum by (request_uri) (count_over_time({host=~\"$host\"} | json | status = 200 [$__interval]))",
     "legendFormat": "{{request_uri}}"
    }
   ]
  },
  { "title": "Technical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{host=~\"$host\"} | json | unwrap request_time [$__interval]) by (host)",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "max by (host) (max_over_time({host=~\"$host\"} | json | unwrap request_time  [$__interval]))",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({host=~\"$host\"} | json [$__interval]))",
     "legendFormat": "HTTP Status {{status}}"
    }
   ]
  },
  {
   "title": "User Agents",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (http_user_agent) (count_over_time({host=~\"$host\"} | json [$__interval]))",
     "legendFormat": "{{http_user_agent}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 38 },
   "targets": [
    {
     "expr": "{host=~\"$host\"} | json | line_format \"{{.request_uri}} with HTTP status: {{.status}}\""
    }
   ]
  },
  { "title": "Heatmap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Country",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 50 },
   "targets": [
    { "panelId": 14 }
   ]
  },
  {
   "title": "Requested Pages",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 66 },
   "targets": [
    { "panelId": 24 }
   ]
  }
 ]
}