name: Build

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install docs tools
        run: yarn

      - name: Build docs
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build.zip
          path: build
